# Use case configuration for Nothing Phone (1)
# Author: Danila Tikhonov <danila@jiaxyga.com>

SectionVerb {
	EnableSequence [
		# PRIMARY NXP TFA9873 PLAYBACK
		cset "name='PRI_MI2S_RX Audio Mixer MultiMedia1' 1"
	]

	DisableSequence [
		# PRIMARY NXP TFA9873 PLAYBACK
		cset "name='PRI_MI2S_RX Audio Mixer MultiMedia1' 0"
	]

	Value {
		TQ "HiFi"
	}
}

SectionDevice."Speaker" {
	Comment "Speaker playback"

	Value {
		PlaybackChannels 2
		PlaybackPriority 100
		PlaybackPCM "hw:${CardId},0"
		PlaybackMixer "default:${CardId}"
	}
}
